#ifndef P2P_CONFIG_H
#define P2P_CONFIG_H

#define NODE_ID_SIZE_BYTES 16
#define NODE_ID_SIZE_BITS NODE_ID_SIZE_BYTES * 8
#define NODE_ID_HASH_BASE 123

#define MAX_UDP_PACKET_SIZE_BYTES 470

#define DEFAULT_UDP_PORT 4075

#define MAX_NODES_IN_KBUCKET 10
#define MAX_FIND_NODE_ITERATIONS 5
#define FIND_NODE_TIMEOUT_IN_MILLISECONDS 10000
#define FIND_NODE_TIMEOUT_THRESHOLD_TO_CONTINUE 0.5

#define MAX_STORE_VALUE_REQUEST_ATTEMPTS 3
#define STORE_VALUE_REQUEST_TIMEOUT_IN_MILLISECONDS 3000

#define MAX_GET_VALUE_REQUEST_ATTEMPTS 3
#define GET_VALUE_REQUEST_TIMEOUT_IN_MILLISECONDS 3000

#define MAX_UNANSWERED_TIME_IN_SECONDS 30
#define PING_DELAY 10

#define RUDP_BLOCKS_IN_SEQUENCE 256
#define RUDP_CONNECTION_TIMEOUT_IN_SECONDS 30
#define RUDP_CONNECTION_ATTEMPTS 10

#endif
